# See https://github.com/linuxdeploy/linuxdeploy/releases for latest release of Linux deploy tool

appimage:
	$(MAKE) install DESTDIR=$(CURDIR)/AppDir
	./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
