appimage: linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage
	$(MAKE) install DESTDIR=$(CURDIR)/AppDir
	./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage

linuxdeploy-x86_64.AppImage:
	wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
	chmod a+x $@

linuxdeploy-plugin-qt-x86_64.AppImage:
	wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
	chmod a+x $@
