# See https://github.com/linuxdeploy/linuxdeploy/releases for latest release of Linux deploy tool.
# See https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases for latest release of Qt plugin.

VERSION=$(shell grep AC_INIT configure.ac | sed -e "s/.*\[\([0-9\.]*\)\].*/\1/")

appimage:
	tar xJf anymeal.tar.xz
	cd anymeal-$(VERSION) && ./configure && $(MAKE) clean all && $(MAKE) install DESTDIR=$(CURDIR)/AppDir && cd ..
	./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage
